# Generated by Django 4.2.7 on 2025-07-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'ordering': ['-created_at'], 'verbose_name': "Appel d'offre", 'verbose_name_plural': "Appels d'offres"},
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Budget du projet', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Date de début du projet (compatibilité)', null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Date de fin du projet (compatibilité)', null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='nom_projet',
            field=models.CharField(default='', help_text='Nom du projet (compatibilité)', max_length=200),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='statut',
            field=models.CharField(choices=[('A_venir', 'À venir'), ('En_cours', 'En cours'), ('Termine', 'Terminé'), ('Annule', 'Annulé')], default='A_venir', max_length=20),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='client',
            field=models.CharField(blank=True, default='', help_text='Nom du client ou organisme', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='critere_evaluation',
            field=models.TextField(blank=True, default='', help_text="Critères d'évaluation des offres", null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Description détaillée de l'appel d'offre", null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='documents',
            field=models.TextField(blank=True, default='', help_text='Liens vers les documents ou fichiers joints', null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='titre',
            field=models.CharField(default='', help_text="Titre de l'appel d'offre", max_length=500),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='type_d_appel_d_offre',
            field=models.CharField(blank=True, default="Appel d'offres", help_text="Type d'appel d'offre (consultation, appel d'offres ouvert, etc.)", max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['date_debut'], name='consultants_date_de_68e31f_idx'),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['date_fin'], name='consultants_date_fi_d0e650_idx'),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['statut'], name='consultants_statut_89de73_idx'),
        ),
    ]
