# Generated by Django 4.2.7 on 2025-07-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_alter_appeloffre_options_appeloffre_budget_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'ordering': ['-date_de_publication', '-created_at'], 'verbose_name': "Appel d'offre", 'verbose_name_plural': "Appels d'offres"},
        ),
        migrations.RemoveIndex(
            model_name='appeloffre',
            name='consultants_date_de_68e31f_idx',
        ),
        migrations.RemoveIndex(
            model_name='appeloffre',
            name='consultants_date_fi_d0e650_idx',
        ),
        migrations.RemoveIndex(
            model_name='appeloffre',
            name='consultants_statut_89de73_idx',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='nom_projet',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='statut',
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='client',
            field=models.CharField(blank=True, help_text='Nom du client ou organisme', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='critere_evaluation',
            field=models.TextField(blank=True, help_text="Critères d'évaluation des offres", null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='description',
            field=models.TextField(blank=True, help_text="Description détaillée de l'appel d'offre", null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='documents',
            field=models.TextField(blank=True, help_text='Liens vers les documents ou fichiers joints', null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='titre',
            field=models.CharField(help_text="Titre de l'appel d'offre", max_length=500),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='type_d_appel_d_offre',
            field=models.CharField(blank=True, help_text="Type d'appel d'offre (consultation, appel d'offres ouvert, etc.)", max_length=200, null=True),
        ),
    ]
