# Generated by Django 4.2.7 on 2025-08-03 03:33

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone  # Ajout de l'import


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0003_alter_appeloffre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-date_validation'], 'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        # Correction ici : suppression du default=4
        migrations.AddField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Faible'), ('NORMAL', 'Normale'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='consultants.mission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_debut',
            field=models.DateField(help_text='Date de début de la mission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_fin',
            field=models.DateField(help_text='Date de fin de la mission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut',
            field=models.CharField(choices=[('En_attente', 'En attente'), ('Validée', 'Validée'), ('En_cours', 'En cours'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='Validée', max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='titre',
            field=models.CharField(help_text='Titre de la mission', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='consultants.matchingresult'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MATCH_VALID', 'Validation de matching'), ('NEW_OFFER', 'Nouvelle offre'), ('MISSION_START', 'Début de mission'), ('MISSION_END', 'Fin de mission'), ('MISSION_UPDATE', 'Mise à jour de mission'), ('SYSTEM', 'Notification système'), ('MATCH_SUGGEST', 'Suggestion de matching'), ('ADMIN_INFO', 'Information administrative'), ('PROFILE_UPDATE', 'Mise à jour de profil'), ('CV_PROCESSED', 'CV traité'), ('EXPERTISE_UPDATE', 'Expertise mise à jour')], default='SYSTEM', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['consultant', 'statut'], name='consultants_consult_c0d4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['appel_offre'], name='consultants_appel_o_ba17ae_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['date_debut', 'date_fin'], name='consultants_date_de_643944_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['consultant', 'is_read'], name='consultants_consult_f4639e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='consultants_type_03757a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'is_read'], name='consultants_priorit_ae1e28_idx'),
        ),
    ]