# Generated by Django 4.2.7 on 2025-07-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0019_sync_fields_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuiviProjet',
        ),
    ]
