# Generated by Django 4.2.7 on 2025-07-15 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0020_delete_suiviprojet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'ordering': ['-id'], 'verbose_name': "Appel d'offre", 'verbose_name_plural': "Appels d'offres"},
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_de_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='lien_site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='type_d_appel_d_offre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='nom_projet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='statut',
            field=models.CharField(blank=True, choices=[('A_venir', 'À venir'), ('En_cours', 'En cours'), ('Termine', 'Terminé')], default='A_venir', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='appeloffre',
            table='apple_offre_appeloffre',
        ),
    ]
