# Generated by Django 4.2.7 on 2025-07-15 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0021_alter_appeloffre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'ordering': ['-created_at'], 'verbose_name': "Appel d'offre", 'verbose_name_plural': "Appels d'offres"},
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='date_de_publication',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='date_limite',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='lien_site',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='type_d_appel_d_offre',
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='client',
            field=models.CharField(default='Client inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='description',
            field=models.TextField(default='Aucune description fournie'),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='nom_projet',
            field=models.CharField(default='Projet sans nom', max_length=200),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='statut',
            field=models.CharField(choices=[('A_venir', 'À venir'), ('En_cours', 'En cours'), ('Termine', 'Terminé')], default='A_venir', max_length=20),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='appeloffre',
            table=None,
        ),
    ]
