# Generated by Django 4.2.7 on 2025-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0022_alter_appeloffre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='client',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
