# Generated by Django 4.2.7 on 2025-07-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0023_alter_appeloffre_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='client',
            field=models.CharField(default='Client inconnu', max_length=191),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='nom_projet',
            field=models.CharField(default='Projet sans nom', max_length=191),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
