# Generated by Django 4.2.7 on 2025-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0024_alter_appeloffre_client_alter_appeloffre_nom_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='cvFilename',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='specialite',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='standardizedCvFilename',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='criteresevaluation',
            name='nom_critere',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='cvrichatgenerated',
            name='filename',
            field=models.CharField(max_length=191, verbose_name='Nom du fichier'),
        ),
        migrations.AlterField(
            model_name='documentged',
            name='tags',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='documentged',
            name='title',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='mission',
            name='titre',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nom',
            field=models.CharField(max_length=191),
        ),
    ]
