# Generated by Django 4.2.7 on 2025-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_documentged_folder_type_alter_documentged_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='nom_competence',
            field=models.CharField(max_length=191),
        ),
    ]
