# Generated by Django 4.2.7 on 2025-05-08 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0005_alter_competence_nom_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_appel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultants.appeloffre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MATCH_VALID', 'Validation de matching'), ('NEW_OFFER', 'Nouvelle offre'), ('SYSTEM', 'Notification système')], default='SYSTEM', max_length=20),
        ),
    ]
