# Generated by Django 4.2.7 on 2025-05-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0006_alter_notification_related_appel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_appel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='consultants.appeloffre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MATCH_SUGGEST', 'Suggestion de matching'), ('MATCH_VALID', 'Validation de matching'), ('ADMIN_INFO', 'Information administrative')], max_length=20),
        ),
    ]
