# Generated by Django 4.2.7 on 2025-05-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0007_alter_notification_related_appel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MATCH_VALID', 'Validation de matching'), ('NEW_OFFER', 'Nouvelle offre'), ('SYSTEM', 'Notification système'), ('MATCH_SUGGEST', 'Suggestion de matching'), ('ADMIN_INFO', 'Information administrative')], default='SYSTEM', max_length=20),
        ),
    ]
