# Generated by Django 4.2.7 on 2025-05-18 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0009_notification_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('REQUIRED_FIELD', 'Champ obligatoire'), ('FORMAT_CHECK', 'Vérification de format'), ('LENGTH_CHECK', 'Vérification de longueur'), ('CONTENT_CHECK', 'Vérification de contenu')], max_length=20)),
                ('field_path', models.CharField(max_length=200)),
                ('validation_config', models.JSONField(default=dict)),
                ('error_message', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('ERROR', 'Erreur'), ('WARNING', 'Avertissement')], default='ERROR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_cv', models.FileField(blank=True, null=True, upload_to='cv_transformations/original/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('richat_stamp', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('template_version', models.CharField(default='v2.0', max_length=20)),
                ('status', models.CharField(choices=[('UPLOADED', 'CV téléchargé'), ('EXTRACTED', 'Données extraites'), ('TRANSFORMED', 'Transformé au format Richat'), ('VALIDATED', 'Validé et signé'), ('ERROR', 'Erreur lors du processus')], default='UPLOADED', max_length=20)),
                ('transformation_date', models.DateTimeField(auto_now_add=True)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.JSONField(blank=True, default=dict)),
                ('is_signed', models.BooleanField(default=False)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_transformations', to='consultants.consultant')),
                ('richat_cv_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_transformation', to='consultants.documentged')),
            ],
            options={
                'verbose_name': 'Transformation CV',
                'verbose_name_plural': 'Transformations CV',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('template_config', models.JSONField(default=dict)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='cv_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
