# Generated by Django 4.2.7 on 2025-06-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0010_cvvalidationrule_cvtransformation_cvtemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cvtemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cvtransformation',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='cvtransformation',
            name='richat_cv_document',
        ),
        migrations.DeleteModel(
            name='CVValidationRule',
        ),
        migrations.AddField(
            model_name='documentged',
            name='file_exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentged',
            name='last_file_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentged',
            name='folder_type',
            field=models.CharField(choices=[('AO_ADMIN', 'Dossier administratif (A.O)'), ('AO_TECHNIQUE', 'Dossier technique (A.O)'), ('AO_FINANCE', 'Dossier financier (A.O)'), ('AMI_CONTEXTE', 'Contexte (A.M.I)'), ('AMI_OUTREACH', 'Outreach (A.M.I)'), ('GENERAL', 'Général')], default='GENERAL', max_length=20),
        ),
        migrations.DeleteModel(
            name='CVTemplate',
        ),
        migrations.DeleteModel(
            name='CVTransformation',
        ),
    ]
