# Generated by Django 4.2.7 on 2025-06-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0011_alter_cvtemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='consultants/photos/'),
        ),
    ]
