# Generated by Django 4.2.7 on 2025-06-13 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0012_consultant_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'ordering': ['-created_at'], 'verbose_name': "Appel d'offre", 'verbose_name_plural': "Appels d'offres"},
        ),
        migrations.AlterModelOptions(
            name='consultant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Consultant', 'verbose_name_plural': 'Consultants'},
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='status',
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=20),
        ),
        migrations.AddField(
            model_name='consultant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='client',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='nom_projet',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='statut',
            field=models.CharField(choices=[('A_venir', 'À venir'), ('En_cours', 'En cours'), ('Termine', 'Terminé')], default='A_venir', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='date_debut_dispo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='date_fin_dispo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='domaine_principal',
            field=models.CharField(choices=[('DIGITAL', 'Digital et Télécoms'), ('FINANCE', 'Secteur bancaire et financier'), ('ENERGIE', 'Transition énergétique'), ('INDUSTRIE', 'Industrie et Mines')], default='DIGITAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='expertise',
            field=models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Expert', 'Expert')], default='Débutant', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='pays',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='specialite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
