# Generated by Django 4.2.7 on 2025-06-13 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0013_add_statut_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.EmailField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['email'], name='consultant_email_idx'),
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['statut'], name='consultant_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['domaine_principal'], name='consultant_domaine_idx'),
        ),
    ]
