# Generated by Django 4.2.7 on 2025-06-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0014_alter_consultant_created_at_alter_consultant_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVRichatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('template_data', models.JSONField(default=dict, verbose_name='Données du template')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template CV Richat',
                'verbose_name_plural': 'Templates CV Richat',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CVRichatGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('cv_data', models.TextField(help_text='Données JSON utilisées pour générer le CV', verbose_name='Données CV')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('quality_score', models.IntegerField(blank=True, help_text='Score de qualité du CV (0-100)', null=True, verbose_name='Score de qualité')),
                ('sections_completed', models.JSONField(default=dict, help_text='Sections complétées dans le CV', verbose_name='Sections complétées')),
                ('download_count', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('last_downloaded', models.DateTimeField(blank=True, null=True, verbose_name='Dernier téléchargement')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richat_cvs', to='consultants.consultant', verbose_name='Consultant')),
            ],
            options={
                'verbose_name': 'CV Richat Généré',
                'verbose_name_plural': 'CV Richat Générés',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['consultant', 'generated_at'], name='consultants_consult_2ffe16_idx'), models.Index(fields=['filename'], name='consultants_filenam_8c49e9_idx'), models.Index(fields=['is_active'], name='consultants_is_acti_a52b67_idx')],
            },
        ),
    ]
